changelog:
  categories:
    - title: Features
      labels: [enhancement]
    - title: Bug Fixes
      labels: [bug]
    - title: Infrastructure
      labels: [infrastructure, ci]
    - title: Other Changes
      labels: ["*"]
